/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/common/AppLayout.vue')['default']
    CalendarHeatmap: typeof import('./components/stats/CalendarHeatmap.vue')['default']
    EmptyChart: typeof import('./components/common/EmptyChart.vue')['default']
    MonthlyChart: typeof import('./components/stats/MonthlyChart.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./components/common/SideNav.vue')['default']
    StatsSummary: typeof import('./components/stats/StatsSummary.vue')['default']
    TagPieChart: typeof import('./components/stats/TagPieChart.vue')['default']
    TaskForm: typeof import('./components/tasks/TaskForm.vue')['default']
    TaskItem: typeof import('./components/tasks/TaskItem.vue')['default']
    TimerControls: typeof import('./components/timer/TimerControls.vue')['default']
    TimerDisplay: typeof import('./components/timer/TimerDisplay.vue')['default']
    TimerRing: typeof import('./components/timer/TimerRing.vue')['default']
    TrendChart: typeof import('./components/stats/TrendChart.vue')['default']
  }
}
